use_frameworks!

target 'VoiceItApi2IosSDK_Example' do
  platform :ios, '10.0'
  pod 'VoiceItApi2IosSDK', :path => '../'
end

target 'VoiceItApi2IosSDK_Test' do
    platform :ios, '10.0'
    inherit! :search_paths
    pod 'VoiceItApi2IosSDK', :path => '../'
end
