use_frameworks!

target 'VoiceIt2-IosSDK_Example' do
  platform :ios, '11.0'
  pod 'VoiceIt2-IosSDK', :path => '../'
end

target 'VoiceIt2-IosSDK_Test' do
    platform :ios, '11.0'
    inherit! :search_paths
    pod 'VoiceIt2-IosSDK', :path => '../'
end
