//
//  VoiceItLogo.m
//  TestingVoiceItAPI2iOSSDKCode
//
//  Created by Armaan Bindra on 10/5/17.
//  Copyright © 2017 VoiceIt Technologies LLC. All rights reserved.
//

#import "VoiceItLogo.h"
#import "Utilities.h"
#import "Styles.h"
@implementation VoiceItLogo

/*
 // Only override drawRect: if you perform custom drawing.
 // An empty implementation adversely affects performance during animation.
 - (void)drawRect:(CGRect)rect {
 // Drawing code
 }
 */
//UIColor* voiceItColor = [Utilities uiColorFromHexString:@"#FFFFFF"];
- (void)drawRect:(CGRect)rect {
    // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
    // http://www.paintcodeapp.com
    
    //// Color Declarations
    UIColor* voiceItColor = [Styles getIconUIColor];// [UIColor colorWithRed: 0.984 green: 0.757 blue: 0.196 alpha: 1];
    //// Group 2
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = [UIBezierPath bezierPath];
        [bezierPath moveToPoint: CGPointMake(18.48, 96.21)];
        [bezierPath addLineToPoint: CGPointMake(71.43, 22.64)];
        [bezierPath addLineToPoint: CGPointMake(71.09, -0.27)];
        [bezierPath addLineToPoint: CGPointMake(0.81, 96.21)];
        [bezierPath addLineToPoint: CGPointMake(18.48, 96.21)];
        [bezierPath closePath];
        bezierPath.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezierPath fill];
        
        
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
        [bezier2Path moveToPoint: CGPointMake(44, 96.21)];
        [bezier2Path addLineToPoint: CGPointMake(96.95, 22.64)];
        [bezier2Path addLineToPoint: CGPointMake(96.61, -0.27)];
        [bezier2Path addLineToPoint: CGPointMake(26.33, 96.21)];
        bezier2Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier2Path fill];
        
        
        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
        [bezier3Path moveToPoint: CGPointMake(43.62, 99.7)];
        [bezier3Path addLineToPoint: CGPointMake(96.57, 173.27)];
        [bezier3Path addLineToPoint: CGPointMake(96.23, 196.18)];
        [bezier3Path addLineToPoint: CGPointMake(25.95, 99.7)];
        [bezier3Path addLineToPoint: CGPointMake(43.62, 99.7)];
        [bezier3Path closePath];
        [bezier3Path moveToPoint: CGPointMake(18.1, 99.7)];
        [bezier3Path addLineToPoint: CGPointMake(71.05, 173.27)];
        [bezier3Path addLineToPoint: CGPointMake(70.71, 196.18)];
        [bezier3Path addLineToPoint: CGPointMake(0.43, 99.7)];
        [bezier3Path addLineToPoint: CGPointMake(18.1, 99.7)];
        [bezier3Path closePath];
        bezier3Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier3Path fill];
        
        
        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = [UIBezierPath bezierPath];
        [bezier4Path moveToPoint: CGPointMake(152.64, 96.3)];
        [bezier4Path addLineToPoint: CGPointMake(99.46, 22.69)];
        [bezier4Path addLineToPoint: CGPointMake(99.81, -0.23)];
        [bezier4Path addLineToPoint: CGPointMake(170.38, 96.3)];
        [bezier4Path addLineToPoint: CGPointMake(152.64, 96.3)];
        [bezier4Path closePath];
        bezier4Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier4Path fill];
        
        
        //// Bezier 5 Drawing
        UIBezierPath* bezier5Path = [UIBezierPath bezierPath];
        [bezier5Path moveToPoint: CGPointMake(127.01, 96.3)];
        [bezier5Path addLineToPoint: CGPointMake(73.84, 22.69)];
        [bezier5Path addLineToPoint: CGPointMake(74.18, -0.23)];
        [bezier5Path addLineToPoint: CGPointMake(144.76, 96.3)];
        bezier5Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier5Path fill];
        
        
        //// Bezier 6 Drawing
        UIBezierPath* bezier6Path = [UIBezierPath bezierPath];
        [bezier6Path moveToPoint: CGPointMake(127.4, 99.79)];
        [bezier6Path addLineToPoint: CGPointMake(74.22, 173.41)];
        [bezier6Path addLineToPoint: CGPointMake(74.56, 196.33)];
        [bezier6Path addLineToPoint: CGPointMake(145.14, 99.79)];
        [bezier6Path addLineToPoint: CGPointMake(127.4, 99.79)];
        [bezier6Path closePath];
        [bezier6Path moveToPoint: CGPointMake(153.02, 99.79)];
        [bezier6Path addLineToPoint: CGPointMake(99.84, 173.41)];
        [bezier6Path addLineToPoint: CGPointMake(100.19, 196.33)];
        [bezier6Path addLineToPoint: CGPointMake(170.77, 99.79)];
        [bezier6Path addLineToPoint: CGPointMake(153.02, 99.79)];
        [bezier6Path closePath];
        bezier6Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier6Path fill];
        
        
        //// Bezier 7 Drawing
        UIBezierPath* bezier7Path = [UIBezierPath bezierPath];
        [bezier7Path moveToPoint: CGPointMake(107.93, 100.3)];
        [bezier7Path addCurveToPoint: CGPointMake(107.76, 102.58) controlPoint1: CGPointMake(107.89, 101.07) controlPoint2: CGPointMake(107.83, 101.83)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 102.58)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 107.15)];
        [bezier7Path addLineToPoint: CGPointMake(107.08, 107.15)];
        [bezier7Path addCurveToPoint: CGPointMake(106.56, 109.44) controlPoint1: CGPointMake(106.93, 107.93) controlPoint2: CGPointMake(106.75, 108.69)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 109.44)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 114)];
        [bezier7Path addLineToPoint: CGPointMake(105.08, 114)];
        [bezier7Path addCurveToPoint: CGPointMake(86.32, 129.99) controlPoint1: CGPointMake(101.34, 123.56) controlPoint2: CGPointMake(94.34, 129.99)];
        [bezier7Path addCurveToPoint: CGPointMake(67.55, 114) controlPoint1: CGPointMake(78.3, 129.99) controlPoint2: CGPointMake(71.3, 123.56)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 114)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 109.44)];
        [bezier7Path addLineToPoint: CGPointMake(66.08, 109.44)];
        [bezier7Path addCurveToPoint: CGPointMake(65.55, 107.15) controlPoint1: CGPointMake(65.88, 108.69) controlPoint2: CGPointMake(65.71, 107.93)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 107.15)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 102.58)];
        [bezier7Path addLineToPoint: CGPointMake(64.88, 102.58)];
        [bezier7Path addCurveToPoint: CGPointMake(64.71, 100.3) controlPoint1: CGPointMake(64.8, 101.83) controlPoint2: CGPointMake(64.75, 101.07)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 100.3)];
        [bezier7Path addLineToPoint: CGPointMake(74.54, 95.73)];
        [bezier7Path addLineToPoint: CGPointMake(64.71, 95.73)];
        [bezier7Path addCurveToPoint: CGPointMake(86.32, 66.05) controlPoint1: CGPointMake(65.5, 79.14) controlPoint2: CGPointMake(74.88, 66.05)];
        [bezier7Path addCurveToPoint: CGPointMake(107.93, 95.73) controlPoint1: CGPointMake(97.76, 66.05) controlPoint2: CGPointMake(107.13, 79.14)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 95.73)];
        [bezier7Path addLineToPoint: CGPointMake(98.86, 100.3)];
        [bezier7Path addLineToPoint: CGPointMake(107.93, 100.3)];
        [bezier7Path closePath];
        bezier7Path.usesEvenOddFillRule = YES;
        [voiceItColor setFill];
        [bezier7Path fill];
    }
}

@end
